[theme]
base = "dark"
backgroundColor = "#000000"
secondaryBackgroundColor = "#0a0a0a"
textColor = "#e6e6e6"
primaryColor = "#3aa3ff"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
